"""add referral_bonus_awarded column

Revision ID: 05fa814e9572
Revises: e1550cd1ffbc
Create Date: 2026-04-11 08:05:13.634850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '05fa814e9572'
down_revision: Union[str, None] = 'e1550cd1ffbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitobxon_users', sa.Column('referral_bonus_awarded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kitobxon_users', 'referral_bonus_awarded')
    # ### end Alembic commands ###
