"""add require_phone_number to quiz settings

Revision ID: 5b45e79f6c88
Revises: 05fa814e9572
Create Date: 2026-04-11 08:40:19.156620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b45e79f6c88'
down_revision: Union[str, None] = '05fa814e9572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitobxon_quiz_settings', sa.Column('require_phone_number', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kitobxon_quiz_settings', 'require_phone_number')
    # ### end Alembic commands ###
