"""add message_id to poll_map

Revision ID: 906802f98e1c
Revises: 5b45e79f6c88
Create Date: 2026-04-11 08:53:44.334210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '906802f98e1c'
down_revision: Union[str, None] = '5b45e79f6c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitobxon_poll_map', sa.Column('message_id', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kitobxon_poll_map', 'message_id')
    # ### end Alembic commands ###
