"""add sent_at to poll_map for time tracking

Revision ID: efd373360b74
Revises: 906802f98e1c
Create Date: 2026-04-11 08:58:00.507800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'efd373360b74'
down_revision: Union[str, None] = '906802f98e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitobxon_poll_map', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kitobxon_poll_map', 'sent_at')
    # ### end Alembic commands ###
